import createClient, { type Middleware } from "openapi-fetch"
import type { paths, components } from "./schema.d" // generated by openapi-typescript
import { env } from "../config/env"

let isRefreshing = false
let failedQueue: Array<{
	resolve: (value?: unknown) => void
	reject: (reason?: unknown) => void
}> = []

const processQueue = (error: Error | null) => {
	failedQueue.forEach((prom) => {
		if (error) {
			prom.reject(error)
		} else {
			prom.resolve()
		}
	})
	failedQueue = []
}

const authMiddleware: Middleware = {
	async onRequest({ request }) {
		const modifiedRequest = new Request(request, {
			credentials: "include",
		})
		// Clone request to save body for potential retry in case of 401
		const retryRequest = modifiedRequest.clone()
		// @ts-ignore
		modifiedRequest._retryRequest = retryRequest

		return modifiedRequest
	},
	async onResponse({ response, request }) {
		// Если ответ успешный, возвращаем его как есть
		if (response.ok) {
			return response
		}

		// Обрабатываем только 401 ошибки
		if (response.status === 401) {
			// Use saved clone if available, otherwise try to clone (will fail if body used)
			// @ts-ignore
			const originalRequest = request._retryRequest || request.clone()

			// Если уже идет обновление токена, добавляем запрос в очередь
			if (isRefreshing) {
				try {
					await new Promise((resolve, reject) => {
						failedQueue.push({ resolve, reject })
					})
					return fetch(originalRequest)
				} catch {
					// Возвращаем оригинальный 401 ответ
					return response
				}
			}

			isRefreshing = true

			try {
				const refreshResponse = await fetch(
					`${env.VITE_URL_TO_BACKEND}/api/auth/refresh`,
					{
						method: "POST",
						credentials: "include",
					},
				)

				if (refreshResponse.ok) {
					processQueue(null)
					isRefreshing = false
					// Повторяем оригинальный запрос
					return fetch(originalRequest)
				} else {
					// Refresh не удался
					processQueue(new Error("Failed to refresh token"))
					isRefreshing = false
					// Возвращаем оригинальный 401 ответ
					return response
				}
			} catch (error) {
				processQueue(error as Error)
				isRefreshing = false
				// Возвращаем оригинальный 401 ответ
				return response
			}
		}

		// Для всех остальных ошибок возвращаем response как есть
		return response
	},
}
console.log(env.VITE_URL_TO_BACKEND)
export const client = createClient<paths>({ baseUrl: env.VITE_URL_TO_BACKEND })
client.use(authMiddleware)
export type DTO = components["schemas"]
