import createClient, { type Middleware } from "openapi-fetch"
import type { paths, components } from "./schema.d" // generated by openapi-typescript
import { env } from "../config/env"

let isRefreshing = false
let failedQueue: Array<{
	resolve: (value?: unknown) => void
	reject: (reason?: unknown) => void
}> = []

const processQueue = (error: Error | null) => {
	failedQueue.forEach((prom) => {
		if (error) {
			prom.reject(error)
		} else {
			prom.resolve()
		}
	})
	failedQueue = []
}

const authMiddleware: Middleware = {
	async onRequest({ request }) {
		const modifiedRequest = new Request(request, {
			credentials: "include",
		})
		return modifiedRequest
	},
	async onResponse({ response, request }) {
		if (response.ok) {
			return response
		}

		if (response.status === 401) {
			const originalRequest = request.clone()

			// Если уже идет обновление токена, добавляем запрос в очередь
			if (isRefreshing) {
				return new Promise((resolve, reject) => {
					failedQueue.push({ resolve, reject })
				})
					.then(() => {
						return fetch(originalRequest)
					})
					.catch((err) => {
						return Promise.reject(err)
					})
			}

			isRefreshing = true

			try {
				const refreshResponse = await fetch(
					`${env.VITE_URL_TO_BACKEND}/api/auth/refresh`,
					{
						method: "POST",
						credentials: "include",
					},
				)

				if (refreshResponse.ok) {
					processQueue(null)
					isRefreshing = false

					return fetch(originalRequest)
				} else {
					processQueue(new Error("Failed to refresh token"))
					isRefreshing = false
					throw new Error("Failed to refresh token")
				}
			} catch (error) {
				processQueue(error as Error)
				isRefreshing = false
				throw error
			}
		}

		return response
	},
}

export const client = createClient<paths>({ baseUrl: env.VITE_URL_TO_BACKEND })
client.use(authMiddleware)
export type DTO = components["schemas"]
