FROM node:20-slim

RUN apt-get update && apt-get install -y procps openssl && rm -rf /var/lib/apt/lists/*

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY .npmrc package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

EXPOSE 3000

CMD ["sh", "-c", "npx prisma generate && pnpm start:dev"]