FROM node:20-slim

RUN apt-get update && apt-get install -y procps openssl rsync && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY services/api-gateway/.npmrc services/api-gateway/package.json services/api-gateway/package-lock.json ./

RUN npm ci

COPY services/shared-types /app/shared-types

RUN cd /app/shared-types && npm ci && npm run build

COPY services/api-gateway .

EXPOSE 3000

CMD sh -c "npm run generate && npm run migrate:deploy && npm run start:dev"