/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../app/routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './../../app/routes/_authenticated/route'
import { Route as UnauthenticatedAuthRouteRouteImport } from './../../app/routes/_unauthenticated/auth/route'
import { Route as AuthenticatedDashboardRouteRouteImport } from './../../app/routes/_authenticated/dashboard/route'
import { Route as AuthenticatedDashboardIndexRouteImport } from './../../app/routes/_authenticated/dashboard/index'
import { Route as UnauthenticatedAuthRegisterRouteImport } from './../../app/routes/_unauthenticated/auth/register'
import { Route as UnauthenticatedAuthLoginRouteImport } from './../../app/routes/_unauthenticated/auth/login'
import { Route as AuthenticatedDashboardIdRouteImport } from './../../app/routes/_authenticated/dashboard/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedAuthRouteRoute =
  UnauthenticatedAuthRouteRouteImport.update({
    id: '/_unauthenticated/auth',
    path: '/auth',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)
const UnauthenticatedAuthRegisterRoute =
  UnauthenticatedAuthRegisterRouteImport.update({
    id: '/register',
    path: '/register',
    getParentRoute: () => UnauthenticatedAuthRouteRoute,
  } as any)
const UnauthenticatedAuthLoginRoute =
  UnauthenticatedAuthLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => UnauthenticatedAuthRouteRoute,
  } as any)
const AuthenticatedDashboardIdRoute =
  AuthenticatedDashboardIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/auth': typeof UnauthenticatedAuthRouteRouteWithChildren
  '/dashboard/$id': typeof AuthenticatedDashboardIdRoute
  '/auth/login': typeof UnauthenticatedAuthLoginRoute
  '/auth/register': typeof UnauthenticatedAuthRegisterRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof UnauthenticatedAuthRouteRouteWithChildren
  '/dashboard/$id': typeof AuthenticatedDashboardIdRoute
  '/auth/login': typeof UnauthenticatedAuthLoginRoute
  '/auth/register': typeof UnauthenticatedAuthRegisterRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRouteWithChildren
  '/_unauthenticated/auth': typeof UnauthenticatedAuthRouteRouteWithChildren
  '/_authenticated/dashboard/$id': typeof AuthenticatedDashboardIdRoute
  '/_unauthenticated/auth/login': typeof UnauthenticatedAuthLoginRoute
  '/_unauthenticated/auth/register': typeof UnauthenticatedAuthRegisterRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/auth'
    | '/dashboard/$id'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/dashboard/$id'
    | '/auth/login'
    | '/auth/register'
    | '/dashboard'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_unauthenticated/auth'
    | '/_authenticated/dashboard/$id'
    | '/_unauthenticated/auth/login'
    | '/_unauthenticated/auth/register'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  UnauthenticatedAuthRouteRoute: typeof UnauthenticatedAuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/auth': {
      id: '/_unauthenticated/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof UnauthenticatedAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
    '/_unauthenticated/auth/register': {
      id: '/_unauthenticated/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof UnauthenticatedAuthRegisterRouteImport
      parentRoute: typeof UnauthenticatedAuthRouteRoute
    }
    '/_unauthenticated/auth/login': {
      id: '/_unauthenticated/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof UnauthenticatedAuthLoginRouteImport
      parentRoute: typeof UnauthenticatedAuthRouteRoute
    }
    '/_authenticated/dashboard/$id': {
      id: '/_authenticated/dashboard/$id'
      path: '/$id'
      fullPath: '/dashboard/$id'
      preLoaderRoute: typeof AuthenticatedDashboardIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRouteRoute
    }
  }
}

interface AuthenticatedDashboardRouteRouteChildren {
  AuthenticatedDashboardIdRoute: typeof AuthenticatedDashboardIdRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteRouteChildren: AuthenticatedDashboardRouteRouteChildren =
  {
    AuthenticatedDashboardIdRoute: AuthenticatedDashboardIdRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteRouteWithChildren =
  AuthenticatedDashboardRouteRoute._addFileChildren(
    AuthenticatedDashboardRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRouteRoute:
    AuthenticatedDashboardRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface UnauthenticatedAuthRouteRouteChildren {
  UnauthenticatedAuthLoginRoute: typeof UnauthenticatedAuthLoginRoute
  UnauthenticatedAuthRegisterRoute: typeof UnauthenticatedAuthRegisterRoute
}

const UnauthenticatedAuthRouteRouteChildren: UnauthenticatedAuthRouteRouteChildren =
  {
    UnauthenticatedAuthLoginRoute: UnauthenticatedAuthLoginRoute,
    UnauthenticatedAuthRegisterRoute: UnauthenticatedAuthRegisterRoute,
  }

const UnauthenticatedAuthRouteRouteWithChildren =
  UnauthenticatedAuthRouteRoute._addFileChildren(
    UnauthenticatedAuthRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  UnauthenticatedAuthRouteRoute: UnauthenticatedAuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
