FROM node:20-slim

RUN apt-get update && apt-get install -y procps openssl rsync && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY services/document-service/package.json services/document-service/package-lock.json ./

RUN npm ci

COPY services/shared-types /app/shared-types

RUN cd /app/shared-types && npm ci && npm run build

COPY services/document-service .

EXPOSE 3001

CMD sh -c "npm run generate && npm run migrate:deploy && npm run start:dev"